### ISSUE TITLE
elastalert2 memory leak

### ISSUE THREAD

**Issue by 08fly** [jertel/elastalert2#1000]
hi
@jertel 
**A memory leak occurs。memory keeps growing
esalert2 version：2.2.1
elasticsearch version： 7.x**
Looking forward to your reply

suspicious logs:

2022-11-08 01:47:26,492    ERROR           elastalert Traceback (most recent call last):
  File "/cib/bin/python3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/cib/bin/python3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/cib/bin/python3.9/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/cib/bin/python3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/cib/bin/python3.9/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/cib/bin/python3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cib/bin/python3.9/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/cib/bin/python3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/cib/bin/python3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/cib/bin/python3.9/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/cib/bin/python3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/cib/bin/python3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/cib/bin/python3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='16.1.34.202', port=9200): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cib/bin/python3.9/lib/python3.9/site-packages/elasticsearch/connection/http_requests.py", line 77, in perform_request
    response = self.session.send(prepared_request, **send_kwargs)
  File "/cib/bin/python3.9/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/cib/bin/python3.9/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='16.1.34.202', port=9200): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cib/bin/python3.9/lib/python3.9/site-packages/elastalert2-2.2.1-py3.9.egg/elastalert/elastalert.py", line 1349, in handle_rule_execution
    num_matches = self.run_rule(rule, endtime, rule.get('initial_starttime'))
  File "/cib/bin/python3.9/lib/python3.9/site-packages/elastalert2-2.2.1-py3.9.egg/elastalert/prometheus_wrapper.py", line 34, in metrics_run_rule
    return self.run_rule(rule, endtime, starttime)
  File "/cib/bin/python3.9/lib/python3.9/site-packages/elastalert2-2.2.1-py3.9.egg/elastalert/elastalert.py", line 946, in run_rule
    if not self.run_query(rule, rule['starttime'], endtime):
  File "/cib/bin/python3.9/lib/python3.9/site-packages/elastalert2-2.2.1-py3.9.egg/elastalert/elastalert.py", line 694, in run_query
    self.thread_data.current_es.clear_scroll(scroll_id=scroll_id)
  File "/cib/bin/python3.9/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/cib/bin/python3.9/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 1289, in clear_scroll
    return self.transport.perform_request(
  File "/cib/bin/python3.9/lib/python3.9/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/cib/bin/python3.9/lib/python3.9/site-packages/elasticsearch/connection/http_requests.py", line 85, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='16.1.34.202', port=9200): Read timed out. (read timeout=20))

2022-11-08 01:47:26,492    ERROR           elastalert Uncaught exception running rule rule_191: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool

**Comment by 08fly** [comment]
And other logs a lot of timeout requests

eg：

2022-11-08 01:49:29,956    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='****', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:50:31,848    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='****', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:51:33,621    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='****', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:52:36,496    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='****', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:53:40,844    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='****', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:54:41,173    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='****', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:55:43,589    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='****', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:56:47,165    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='****', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:57:48,901    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='****', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:59:54,856    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='****', port=9200): Read timed out. (read timeout=20)

**Comment by 08fly** [comment]
2022-11-08 01:49:29,956    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='xxxxx', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:50:31,848    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='xxxxx', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:51:33,621    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='xxxxx', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:52:36,496    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='xxxxx', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:53:40,844    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='xxxxx', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:54:41,173    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='xxxxx', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:55:43,589    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='xxxxx', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:56:47,165    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='xxxxx', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:57:48,901    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='xxxxx', port=9200): Read timed out. (read timeout=20))
2022-11-08 01:59:54,856    ERROR           elastalert Error running query: ConnectionTimeout caused by - ReadTimeout(HTTPConnectionPool(host='xxxxx', port=9200): Read timed out. (read timeout=20)

**Comment by nsano-rururu** [comment]
Check if it happens in the latest version, not the old version!

**Comment by 08fly** [comment]
Is it recommended to upgrade to the latest version?  Because it is an online environment, the upgrade cost is high

**Comment by nsano-rururu** [comment]
I'm talking about the latest version of elastalert2. Although it is OSS. What do you mean?

**Comment by nsano-rururu** [comment]
Have you tried closing or deleting unnecessary past data? . When I store a large amount of metricbeat data, it uses a lot of CPU/memory just by moving it, so I've improved it by closing or deleting data for a certain period of time.

**Comment by nsano-rururu** [comment]
Index Lifecycle Management(ILM)
