### ISSUE TITLE
k8s deploy 

### ISSUE THREAD

**Issue by 1998729** [jertel/elastalert2#1017]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/88186802/202611698-a3d3edaa-52bb-4615-9208-5bd8984788a5.png">

**Comment by 1998729** [comment]
Starting with this parameter does not seem to work. After the image is started, it will let you create an index interactively by default?

**Comment by 1998729** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elastalert/create_index.py", line 188, in main
    host = args.host if args.host else input('Enter Elasticsearch host: ')
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line
Enter Elasticsearch host:

**Comment by 1998729** [comment]
update: 
<img width="677" alt="image" src="https://user-images.githubusercontent.com/88186802/202638430-4c8bceb3-4a7a-4ffb-a623-378e13ac82c9.png">

**Comment by 1998729** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/88186802/202641272-df327211-eba9-4d45-9571-11ad2923b5f2.png">

closed
