### ISSUE TITLE
ERROR:elastalert:Error writing alert info to Elasticsearch: TransportError(405, 'Incorrect HTTP method for uri [/elastalert_status_error/_doc] and method [GET], allowed: [POST]'

### ISSUE THREAD

**Issue by ayoub-elbachiri** [jertel/elastalert2#1167]
**MY CONFIG:**

rules_folder: /opt/elastalert/rules
run_every:
  seconds: 10
buffer_time:
  minutes: 15
index: "x*"
es_send_get_body_as: "POST"
es_host: "x"
es_port: "80"
es_username: "test"
es_password: "test"
use_ssl: False
writeback_index: elastalert_status
alert_time_limit:
  days: 2

**---**

name: test alert
type: frequency
index: y-*
is_enabled: true
smtp_host: smtp.x.x.x
smtp_port: 25
num_events: 2
timeframe:
  hours: 2
filter:
- query:
    query_string:
      query: "error"
alert:
- "email"
email:
- "test@gmail.com"

**LOGS:**

INFO:elastalert:Background alerts thread 0 pending alerts sent at 2023-04-26 11:43 UTC
WARNING:elasticsearch:POST http://x:80/_search/scroll?scroll=30s [status:400 request:0.047s]
ERROR:elastalert:Error running query: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: scrollId is missing;')
WARNING:elasticsearch:POST http://x:80/elastalert_status_error/_doc [status:405 request:0.060s]
ERROR:elastalert:Error writing alert info to Elasticsearch: TransportError(405, 'Incorrect HTTP method for uri [/elastalert_status_error/_doc] and method [GET], allowed: [POST]', 'Incorrect HTTP method for uri [/elastalert_status_error/_doc] and method [GET], allowed: [POST]')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/elastalert/elastalert.py", line 368, in get_hits
    res = self.thread_data.current_es.scroll(scroll_id=rule['scroll_id'], scroll=scroll_keepalive)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/client/__init__.py", line 1504, in scroll
    return self.transport.perform_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/connection/http_requests.py", line 199, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/connection/base.py", line 315, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: scrollId is missing;')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/elastalert/elastalert.py", line 1456, in writeback
    res = self.writeback_es.index(index=index, body=body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/client/__init__.py", line 398, in index
    return self.transport.perform_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/connection/http_requests.py", line 199, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/connection/base.py", line 315, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.TransportError: TransportError(405, 'Incorrect HTTP method for uri [/elastalert_status_error/_doc] and method [GET], allowed: [POST]', 'Incorrect HTTP method for uri [/elastalert_status_error/_doc] and method [GET], allowed: [POST]')

**Comment by jertel** [comment]
I recommend turning on debug logging so we can see more details on what's going on and what specifically it's attempting to send to Elasticsearch.
