### ISSUE TITLE
2.17.0 AttributeError: module 'datetime' has no attribute 'UTC'

### ISSUE THREAD

**Issue by buzzdeee** [jertel/elastalert2#1400]
Just installed elastalert2 on Ubuntu 22.04.4 LTS, with Python 3.10.12, and python-dateutil           2.9.0.post0, starting elastalert I see:

```
Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/elastalert/elastalert.py", line 1926, in main
    client.start()
  File "/usr/local/lib/python3.10/dist-packages/elastalert/elastalert.py", line 1161, in start
    if next_run < datetime.datetime.now(tz=datetime.UTC):
AttributeError: module 'datetime' has no attribute 'UTC'


Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/elastalert/elastalert.py", line 1926, in main
    client.start()
  File "/usr/local/lib/python3.10/dist-packages/elastalert/elastalert.py", line 1161, in start
    if next_run < datetime.datetime.now(tz=datetime.UTC):
AttributeError: module 'datetime' has no attribute 'UTC'

```

there are a few more places, but replacing all of the: 
````
datetime.UTC
``````
 with 
``````
datetime.timezone.utc
```````

made it properly start up for me.

**Comment by jertel** [comment]
The `datetime.UTC` alias was introduced after Python 3.10. Per the ElastAlert 2 docs, this project requires Python 3.12.

![image](https://github.com/jertel/elastalert2/assets/16639611/b4d8462f-17da-4a53-929b-8b6d9d66a58f)

If you are unable to install or update Python on your host OS you can consider using the Docker image instead: https://elastalert2.readthedocs.io/en/latest/running_elastalert.html#as-a-docker-container

**Comment by buzzdeee** [comment]
thank you, I was updating from an older Ubuntu with older elastalert2 version to the versions mentioned above, didn't expect the python 3.12 requirement.
