### ISSUE TITLE
alertmanager alert can't work.

### ISSUE THREAD

**Issue by mikechengwei** [jertel/elastalert2#552]
configuration:
`
alert:
  - "alertmanager"
alertmanager_hosts:
  - "http://alertmanager:9093"
alertmanager_alertname: "Title"
alertmanager_annotations:
  severity: "error"
alertmanager_labels:
  source: "elastalert"
alertmanager_fields:
  msg: "message"
  log: "@log_name"
`

<img width="1048" alt="Screen Shot 2021-11-10 at 9 07 29 PM" src="https://user-images.githubusercontent.com/13257127/141131204-87fc43ba-5606-4845-a836-14dec777baf6.png">

<img width="1636" alt="Screen Shot 2021-11-10 at 9 07 42 PM" src="https://user-images.githubusercontent.com/13257127/141131221-d1275357-552d-493b-b317-9c650b03f775.png">

**Comment by jertel** [comment]
It's not yet released. It will be released this week.

**Comment by thepaleviper** [comment]
**After updating Elastalert to 2.2.3 I am still facing the same issue as Mike.**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/elastalert/util.py", line 27, in get_module
    module_path, module_class = module_name.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/elastalert/loaders.py", line 522, in load_alerts
    alert_field = [create_alert(a, b) for a, b in alert_field]
  File "/usr/local/lib/python3.9/site-packages/elastalert/loaders.py", line 522, in <listcomp>
    alert_field = [create_alert(a, b) for a, b in alert_field]
  File "/usr/local/lib/python3.9/site-packages/elastalert/loaders.py", line 506, in create_alert
    alert_class = self.alerts_mapping.get(alert) or get_module(alert)
  File "/usr/local/lib/python3.9/site-packages/elastalert/util.py", line 31, in get_module
    raise EAException("Could not import module %s: %s" % (module_name, e)).with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.9/site-packages/elastalert/util.py", line 27, in get_module
    module_path, module_class = module_name.rsplit('.', 1)
elastalert.util.EAException: Could not import module alertmananger: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/elastalert/loaders.py", line 162, in load
    rule = self.load_configuration(rule_file, conf, args)
  File "/usr/local/lib/python3.9/site-packages/elastalert/loaders.py", line 225, in load_configuration
    self.load_modules(rule, args)
  File "/usr/local/lib/python3.9/site-packages/elastalert/loaders.py", line 489, in load_modules
    rule['alert'] = self.load_alerts(rule, alert_field=rule['alert'])
  File "/usr/local/lib/python3.9/site-packages/elastalert/loaders.py", line 525, in load_alerts
    raise EAException('Error initiating alert %s: %s' % (rule['alert'], e)).with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.9/site-packages/elastalert/loaders.py", line 522, in load_alerts
    alert_field = [create_alert(a, b) for a, b in alert_field]
  File "/usr/local/lib/python3.9/site-packages/elastalert/loaders.py", line 522, in <listcomp>
    alert_field = [create_alert(a, b) for a, b in alert_field]
  File "/usr/local/lib/python3.9/site-packages/elastalert/loaders.py", line 506, in create_alert
    alert_class = self.alerts_mapping.get(alert) or get_module(alert)
  File "/usr/local/lib/python3.9/site-packages/elastalert/util.py", line 31, in get_module
    raise EAException("Could not import module %s: %s" % (module_name, e)).with_traceback(sys.exc_info()[2])
  File "/usr/local/lib/python3.9/site-packages/elastalert/util.py", line 27, in get_module
    module_path, module_class = module_name.rsplit('.', 1)
elastalert.util.EAException: Error initiating alert ['alertmananger']: Could not import module alertmananger: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/elastalert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/elastalert/elastalert.py", line 2155, in main
    client = ElastAlerter(args)
  File "/usr/local/lib/python3.9/site-packages/elastalert/elastalert.py", line 128, in __init__
    self.rules = self.rules_loader.load(self.conf, self.args)
  File "/usr/local/lib/python3.9/site-packages/elastalert/loaders.py", line 170, in load
    raise EAException('Error loading file %s: %s' % (rule_file, e))
elastalert.util.EAException: Error loading file /etc/elastalert/rules/ssh_maximum_attempts.yaml: Error initiating alert ['alertmananger']: Could not import module alertmananger: not enough values to unpack (expected 2, got 1)

```
My rule file

```
name: SSH MAximum Failed Login

type: frequency

num_events: 2

timeframe:
  minutes: 10

filter:
- term:
    rule.description : "Maximum authentication attempts exceeded."

index: wazuh-alerts-*

alert:
  - "alertmananger"
alertmanager_hosts:
  - "http://10.55.2.89:9093"
```

**Comment by jertel** [comment]
You spelled `alertmananger` wrong.

**Comment by thepaleviper** [comment]
> You spelled `alertmananger` wrong.

Oh! my bad.
Thank you!
