### ISSUE TITLE
Error while testing alert 

### ISSUE THREAD

**Issue by agarwalamal** [jertel/elastalert2#753]
PS E:\ELK\elastalert2-master> elastalert-test-rule examples/rules/example_frequency.yaml
Traceback (most recent call last):
  File "C:\Program Files\Python310\Scripts\elastalert-test-rule-script.py", line 33, in <module>
    sys.exit(load_entry_point('elastalert2==2.3.0', 'console_scripts', 'elastalert-test-rule')())
  File "C:\Program Files\Python310\Scripts\elastalert-test-rule-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Program Files\Python310\lib\importlib\metadata\__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Python310\lib\site-packages\elastalert-0.2.4-py3.10.egg\elastalert\test_rule.py", line 15, in <module>
    from elastalert.config import load_conf
  File "C:\Program Files\Python310\lib\site-packages\elastalert-0.2.4-py3.10.egg\elastalert\config.py", line 9, in <module>
    from . import loaders
  File "C:\Program Files\Python310\lib\site-packages\elastalert-0.2.4-py3.10.egg\elastalert\loaders.py", line 16, in <module>
    from . import ruletypes
  File "C:\Program Files\Python310\lib\site-packages\elastalert-0.2.4-py3.10.egg\elastalert\ruletypes.py", line 6, in <module>
    from blist import sortedlist
ImportError: cannot import name 'sortedlist' from 'blist' (C:\Program Files\Python310\lib\site-packages\blist\__init__.py)
PS E:\ELK\elastalert2-master>

**Comment by jertel** [comment]
Please do not post errors related to Yelp's ElastAlert project. This project is for _ElastAlert 2_ only.

**Comment by agarwalamal** [comment]
I got this error using alert2, as mention in first time user guide

**Comment by jertel** [comment]
You are still using the old elastalert. This is clear from several of the error lines you pasted:

```
File "C:\Program Files\Python310\lib\site-packages\elastalert-0.2.4-py3.10.egg\elastalert\ruletypes.py", line 6, in
from blist import sortedlist
```

Please review the project guidelines as mentioned in #11.

**Comment by agarwalamal** [comment]
I uninstalled and installed python and removed old elastic alert, I will
try to clear out everything again and check again tomorrow. Thanks will
confirm

Thanks,
Amal

**Comment by agarwalamal** [comment]
i tried removing that package and clone the current git and i am getting and error with python elastalert/elastalert.py

PS E:\ELK\elastalert2-master> python elastalert/elastalert.py
Traceback (most recent call last):
  File "E:\ELK\elastalert2-master\elastalert\elastalert.py", line 32, in <module>
    from elastalert.alerters.debug import DebugAlerter
  File "E:\ELK\elastalert2-master\elastalert\elastalert.py", line 32, in <module>
    from elastalert.alerters.debug import DebugAlerter
ModuleNotFoundError: No module named 'elastalert.alerters'; 'elastalert' is not a package
PS E:\ELK\elastalert2-master>

**Comment by jertel** [comment]
There are two supported methods of running ElastAlert 2, documented [here](https://elastalert2.readthedocs.io/en/latest/running_elastalert.html)
1. Use the official Docker container
2. Use the official Python pip package.

You mentioned using git to clone the repo with the ElastAlert 2 source code. This is not recommended, but it can be done, provided you are experienced with Python development.

**Comment by agarwalamal** [comment]
thank that helped, i am getting an error  ERROR:elastalert:Uncaught
exception running rule Example frequency rule: (501, b'5.1.7 Invalid
address', 'ElastAlert')

PS E:\ELK\elastalert2-master> python -m elastalert.elastalert --config
E:\ELK\elastalert2-master\examples\config.yaml --verbose --rule
example_frequency.yaml
INFO:elastalert:1 rules loaded
INFO:elastalert:Starting up
INFO:elastalert:Disabled rules are: []
INFO:elastalert:Sleeping for 60.0 seconds
INFO:elastalert:Queried rule Example frequency rule from 2022-03-10 15:28
Eastern Standard Time to 2022-03-10 15:43 Eastern Standard Time: 270 / 270
hits
INFO:elastalert:Queried rule Example frequency rule from 2022-03-10 15:43
Eastern Standard Time to 2022-03-10 15:51 Eastern Standard Time: 141 / 141
hits
ERROR:elastalert:Traceback (most recent call last):
  File "E:\ELK\elastalert2-master\elastalert\elastalert.py", line 1298, in
alert
    return self.send_alert(matches, rule, alert_time=alert_time,
retried=retried)
  File "E:\ELK\elastalert2-master\elastalert\elastalert.py", line 1375, in
send_alert
    alert.alert(matches)
  File "E:\ELK\elastalert2-master\elastalert\alerters\email.py", line 115,
in alert
    self.smtp.sendmail(self.from_addr, to_addr, email_msg.as_string())
  File "C:\Program Files\Python310\lib\smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (501, b'5.1.7 Invalid address', 'ElastAlert')

ERROR:elastalert:Uncaught exception running rule Example frequency rule:
(501, b'5.1.7 Invalid address', 'ElastAlert')

=================================================================================
# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- term:
    monitor.status: "down"

# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to



*smtp_host: "smtp-relay.courts.phila.gov
<http://smtp-relay.courts.phila.gov>"smtp_port: 25email:
***@***.*** ***@***.***>"*

Regards,
Amal
