### ISSUE TITLE
Create index script not working with elasticsearch 8.2

### ISSUE THREAD

**Issue by EtiennePer** [jertel/elastalert2#861]
Hello there, 

I'm facing an issue while trying to use elastalert2 (python package) with elasticsearch 8.2 when running the following command within my container's "entrypoint" 

`elastalert-create-index --config /elastalert/config/config.yml`

```BASH
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/elastalert/create_index.py", line 273, in main
    create_index_mappings(es_client=es, ea_index=index, recreate=args.recreate, old_ea_index=old_index)
  File "/usr/local/lib/python3.6/site-packages/elastalert/create_index.py", line 69, in create_index_mappings
    body=es_index_mappings['elastalert'], include_type_name=True)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 321, in put_mapping
    "PUT", _make_path(index, "_mapping", doc_type), params=params, body=body
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_requests.py", line 91, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 131, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)

elasticsearch.exceptions.RequestError: RequestError(400, 'no handler found for uri [/elastalert_status/_mapping/_doc?include_type_name=true] and method [PUT]', 'no handler found for uri [/elastalert_status/_mapping/_doc?include_type_name=true] and method [PUT]')
```

It appears that the REST API has been updated : 

**current** https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html
**7.17** https://www.elastic.co/guide/en/elasticsearch/reference/7.17/indices-put-mapping.html
I would say that "include_type_name" parameter doesn't exists anymore and is the source of the problem, but I'm not completely sure about that. 

Thanks in advance for any help / fix. 

Etienne

**Comment by jertel** [comment]
I just tried it on a new 8.2.0 install, without issue:

```
$ curl http://localhost:9200
{
  "name" : "fd8b767db9af",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "S9sAJ2YjT8mom0JREUvX7g",
  "version" : {
    "number" : "8.2.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "b174af62e8dd9f4ac4d25875e9381ffe2b9282c5",
    "build_date" : "2022-04-20T10:35:10.180408517Z",
    "build_snapshot" : false,
    "lucene_version" : "9.1.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}

$ docker run --rm -v ... jertel/elastalert2
Error: No such container: ea
Reading Elastic 8 index mappings:
Reading index mapping 'es_mappings/8/silence.json'
Reading index mapping 'es_mappings/8/elastalert_status.json'
Reading index mapping 'es_mappings/8/elastalert.json'
Reading index mapping 'es_mappings/8/past_elastalert.json'
Reading index mapping 'es_mappings/8/elastalert_error.json'
New index elastalert_status created
Done!
```

You are likely running an older version of Python or an outdated version of ElastAlert 2.

Converting this issue into a Q/A discussion.
