### ISSUE TITLE
An error is reported when elastalert is started

### ISSUE THREAD

**Issue by bbzcx** [jertel/elastalert2#965]
I have configured the host in config.yaml, but an error has been reported

EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host: #Traceback (most recent call last):,
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>,
    sys.exit(main()),
  File "/usr/local/lib/python3.10/site-packages/elastalert/create_index.py", line 188, in main,
    host = args.host if args.host else input('Enter Elasticsearch host: '),
EOFError: EOF when reading a line,
Enter Elasticsearch host:

**Comment by jertel** [comment]
It looks like it's can't read the config file properly. Please see #11 before posting issues. Moving this issue to a discussion.
